# Hybrid Models for Recommendation Systems

Load Pandas, we are going to need it for manipulating data

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

Now load the data

In [2]:
user_ratings_df = pd.read_csv("user_ratings.csv")
user_features_df = pd.read_csv("user_features.csv")
item_features_df = pd.read_csv("item_features.csv")

In [3]:

print(user_ratings_df)

   The Call of Cthulhu   Frankenstein   Dracula   Neuromancer   Space Odyssey
0                  8.0            2.0       NaN           5.0             4.0
1                  3.0            2.0       NaN           7.0             7.0
2                  9.0            NaN       7.0           8.0             5.0
3                  NaN            NaN       7.0           8.0             9.0
4                  NaN            1.0       8.0           3.0             7.0
5                  2.0            3.0       5.0           NaN             NaN
6                  4.0            2.0       NaN           2.0             7.0
7                  7.0            1.0       2.0           7.0             9.0
8                  3.0            3.0       NaN           7.0             3.0
9                  4.0            NaN       5.0           3.0             3.0


In [4]:
print(user_features_df)

   Sex   Over60
0  1.0      0.0
1  0.0      1.0
2  0.0      0.0
3  1.0      0.0
4  0.0      1.0
5  0.0      0.0
6  0.0      0.0
7  1.0      0.0
8  0.0      1.0
9  1.0      0.0


In [5]:
print(item_features_df)

   Critic0   Critic1
0      0.3       0.9
1      0.9       0.3
2      0.6       0.4
3      0.2       0.1
4      0.7       0.8


In [6]:
user_features_df["key"] = 0
user_features_df["user_id"] = range(0,user_features_df.shape[0])
item_features_df["key"] = 0
item_features_df["item_id"] = range(0,item_features_df.shape[0])

merged_df = pd.merge(user_features_df,    item_features_df,left_index=True,on="key")
merged_df[["item_id", "user_id"]]




merged_df["rating"] = list(map(lambda ids: user_ratings_df.values[ids[1]][ids[2]], 
                          merged_df[["user_id", "item_id"]].itertuples()))

In [7]:
merged_df

Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
0  1.0      0.0    0        0      0.3       0.9        0     8.0
1  1.0      0.0    0        0      0.9       0.3        1     2.0
2  1.0      0.0    0        0      0.6       0.4        2     NaN
3  1.0      0.0    0        0      0.2       0.1        3     5.0
4  1.0      0.0    0        0      0.7       0.8        4     4.0
0  0.0      1.0    0        1      0.3       0.9        0     3.0
1  0.0      1.0    0        1      0.9       0.3        1     2.0
2  0.0      1.0    0        1      0.6       0.4        2     NaN
3  0.0      1.0    0        1      0.2       0.1        3     7.0
4  0.0      1.0    0        1      0.7       0.8        4     7.0
0  0.0      0.0    0        2      0.3       0.9        0     9.0
1  0.0      0.0    0        2      0.9       0.3        1     NaN
2  0.0      0.0    0        2      0.6       0.4        2     7.0
3  0.0      0.0    0        2      0.2       0.1        3     8.0
4  0.0      0.0    0        2      0.7       0.8        4     5.0
0  1.0      0.0    0        3      0.3       0.9        0     NaN
1  1.0      0.0    0        3      0.9       0.3        1     NaN
2  1.0      0.0    0        3      0.6       0.4        2     7.0
3  1.0      0.0    0        3      0.2       0.1        3     8.0
4  1.0      0.0    0        3      0.7       0.8        4     9.0
0  0.0      1.0    0        4      0.3       0.9        0     NaN
1  0.0      1.0    0        4      0.9       0.3        1     1.0
2  0.0      1.0    0        4      0.6       0.4        2     8.0
3  0.0      1.0    0        4      0.2       0.1        3     3.0
4  0.0      1.0    0        4      0.7       0.8        4     7.0
0  0.0      0.0    0        5      0.3       0.9        0     2.0
1  0.0      0.0    0        5      0.9       0.3        1     3.0
2  0.0      0.0    0        5      0.6       0.4        2     5.0
3  0.0      0.0    0        5      0.2       0.1        3     NaN
4  0.0      0.0    0        5      0.7       0.8        4     NaN
0  0.0      0.0    0        6      0.3       0.9        0     4.0
1  0.0      0.0    0        6      0.9       0.3        1     2.0
2  0.0      0.0    0        6      0.6       0.4        2     NaN
3  0.0      0.0    0        6      0.2       0.1        3     2.0
4  0.0      0.0    0        6      0.7       0.8        4     7.0
0  1.0      0.0    0        7      0.3       0.9        0     7.0
1  1.0      0.0    0        7      0.9       0.3        1     1.0
2  1.0      0.0    0        7      0.6       0.4        2     2.0
3  1.0      0.0    0        7      0.2       0.1        3     7.0
4  1.0      0.0    0        7      0.7       0.8        4     9.0
0  0.0      1.0    0        8      0.3       0.9        0     3.0
1  0.0      1.0    0        8      0.9       0.3        1     3.0
2  0.0      1.0    0        8      0.6       0.4        2     NaN
3  0.0      1.0    0        8      0.2       0.1        3     7.0
4  0.0      1.0    0        8      0.7       0.8        4     3.0
0  1.0      0.0    0        9      0.3       0.9        0     4.0
1  1.0      0.0    0        9      0.9       0.3        1     NaN
2  1.0      0.0    0        9      0.6       0.4        2     5.0
3  1.0      0.0    0        9      0.2       0.1        3     3.0
4  1.0      0.0    0        9      0.7       0.8        4     3.0

In [8]:
train = merged_df.dropna()

test = merged_df[merged_df.isnull().any(axis=1)]

In [9]:

train.head(), test.head()

(   Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
 0  1.0      0.0    0        0      0.3       0.9        0     8.0
 1  1.0      0.0    0        0      0.9       0.3        1     2.0
 3  1.0      0.0    0        0      0.2       0.1        3     5.0
 4  1.0      0.0    0        0      0.7       0.8        4     4.0
 0  0.0      1.0    0        1      0.3       0.9        0     3.0,
    Sex   Over60  key  user_id  Critic0   Critic1  item_id  rating
 2  1.0      0.0    0        0      0.6       0.4        2     NaN
 2  0.0      1.0    0        1      0.6       0.4        2     NaN
 1  0.0      0.0    0        2      0.9       0.3        1     NaN
 0  1.0      0.0    0        3      0.3       0.9        0     NaN
 1  1.0      0.0    0        3      0.9       0.3        1     NaN)

In [10]:
n_latent_features = 2

user_ratings = user_ratings_df.values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_latent_features))

In [11]:
user_features = user_features_df.values
item_features = item_features_df.values

In [12]:
user_features_weights = np.random.random((user_ratings.shape[0], user_features.shape[1] ))
item_features_weights = np.random.random((user_ratings.shape[1], item_features.shape[1] ))

In [13]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    
    user_score = user_features_weights[user_id].dot(user_features[user_id])
    item_score = item_features_weights[item_id].dot(item_features[item_id])
    #print user_preference.dot(item_preference), user_score, item_score
    return user_preference.dot(item_preference) + user_score + item_score

def train(user_id, item_id, rating,alpha = 0.001, 
                                   latent_feature_weight_decay = 0.1, 
                                   user_weight_decay = 0.01,
                                   item_weight_decay = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating - rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err *  ( latent_item_features[item_id] + latent_feature_weight_decay*latent_user_preferences[user_id])
    latent_item_features[item_id] -= alpha * err * ( user_pref_values + latent_feature_weight_decay*latent_item_features[item_id])
    
    user_features_weights[user_id] -=alpha * err *(  user_features[user_id] + user_weight_decay* user_features_weights[user_id])
    item_features_weights[item_id] -=alpha * err * ( item_features_weights[item_id] + item_weight_decay* item_features_weights[item_id])
    
    
    return err
    


def sgd(iterations = 30000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print (mse)
                    
                    
    
                    
                    
    


In [14]:
for _ in range(0,10): 
    sgd()

0.27922687503715704
0.27507336824266904
0.27385359578371077
0.27332910874645416
0.2730755892269549
0.2729571315294969
0.27291784573162037
0.27293118625724067
0.2729834345791762
0.2730672295242411


In [15]:
predictions = np.zeros(shape = (latent_user_preferences.shape[0], latent_item_features.shape[0]) )
#print latent_user_preferences
print (user_features_weights)
print (item_features_weights)
for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                predictions[user_id,item_id] =  predict_rating(user_id,item_id)

  

[[ 0.541  0.414  0.329  0.909]
 [ 0.46  -1.879  0.237 -1.2  ]
 [ 0.608  0.409  0.431  0.589]
 [ 0.853  0.226  0.536  0.532]
 [ 0.507  0.37   0.103 -0.287]
 [ 0.848  0.482  0.152  2.912]
 [ 0.616  0.854  0.953 -0.181]
 [ 0.72   0.743  0.246 -0.008]
 [ 0.382  0.17   0.216 -0.548]
 [ 0.191  0.676  0.192 -0.314]]
[[2.118e+00 2.476e+00 6.090e+00 1.389e+00]
 [1.198e-04 1.266e-04 1.075e-04 8.044e-05]
 [2.777e-02 6.241e-01 5.038e-01 3.270e-02]
 [2.997e+00 4.468e+00 9.016e-02 3.132e-01]
 [2.231e+00 2.501e+00 5.092e+00 2.645e+00]]


In [16]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns =user_ratings_df.columns
comparison_data
#applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

The Call of Cthulhu                 Frankenstein  \
0   (8.0, 7.939267835824895)    (2.0, 2.2260452680486837)   
1   (3.0, 2.903626801630164)     (2.0, 2.364573827748533)   
2    (9.0, 8.93831050921479)     (nan, 4.620093545755054)   
3   (nan, 8.909944727377365)     (nan, 4.960263538595817)   
4   (nan, 4.905511252022392)    (1.0, 0.6857769308947496)   
5  (2.0, 2.0056674197681277)     (3.0, 2.994063023207615)   
6   (4.0, 4.442344239552886)   (2.0, 0.38980307234737305)   
7   (7.0, 6.438865412291259)     (1.0, 2.925960375917761)   
8   (3.0, 3.160630148075664)    (3.0, 2.4223866658915085)   
9   (4.0, 4.166433082499633)  (nan, -0.14838347234027313)   

                     Dracula                 Neuromancer  \
0  (nan, 21.282073697414386)    (5.0, 4.857888304947407)   
1  (nan, -32.39381524728224)    (7.0, 6.769654172003071)   
2  (7.0, 7.0073897698772445)    (8.0, 8.051287220469568)   
3  (7.0, 7.0000440988011885)    (8.0, 7.999308022048608)   
4    (8.0, 8.00662763219522)   (3.0, 3.2645185085601085)   
5  (5.0, 4.9996113147707115)  (nan, 0.09109821047314437)   
6   (nan, 6.293859056240673)   (2.0, 2.9779303905841017)   
7  (2.0, 2.0636470243278824)   (7.0, 5.8706543748267235)   
8  (nan, -34.16196895703029)     (7.0, 7.33896423176618)   
9   (5.0, 4.993048633493229)   (3.0, 2.8690485751145625)   

               Space Odyssey  
0   (4.0, 3.979336350613533)  
1   (7.0, 6.966665946109118)  
2   (5.0, 4.999498086905717)  
3   (9.0, 8.999164535750015)  
4   (7.0, 7.027859893849413)  
5   (nan, 60.65109711753167)  
6   (7.0, 7.143382664224486)  
7   (9.0, 8.832381011610902)  
8  (3.0, 3.0494452637480833)  
9   (3.0, 2.999277022295093)

In [17]:
comparison_data

The Call of Cthulhu                 Frankenstein  \
0   (8.0, 7.939267835824895)    (2.0, 2.2260452680486837)   
1   (3.0, 2.903626801630164)     (2.0, 2.364573827748533)   
2    (9.0, 8.93831050921479)     (nan, 4.620093545755054)   
3   (nan, 8.909944727377365)     (nan, 4.960263538595817)   
4   (nan, 4.905511252022392)    (1.0, 0.6857769308947496)   
5  (2.0, 2.0056674197681277)     (3.0, 2.994063023207615)   
6   (4.0, 4.442344239552886)   (2.0, 0.38980307234737305)   
7   (7.0, 6.438865412291259)     (1.0, 2.925960375917761)   
8   (3.0, 3.160630148075664)    (3.0, 2.4223866658915085)   
9   (4.0, 4.166433082499633)  (nan, -0.14838347234027313)   

                     Dracula                 Neuromancer  \
0  (nan, 21.282073697414386)    (5.0, 4.857888304947407)   
1  (nan, -32.39381524728224)    (7.0, 6.769654172003071)   
2  (7.0, 7.0073897698772445)    (8.0, 8.051287220469568)   
3  (7.0, 7.0000440988011885)    (8.0, 7.999308022048608)   
4    (8.0, 8.00662763219522)   (3.0, 3.2645185085601085)   
5  (5.0, 4.9996113147707115)  (nan, 0.09109821047314437)   
6   (nan, 6.293859056240673)   (2.0, 2.9779303905841017)   
7  (2.0, 2.0636470243278824)   (7.0, 5.8706543748267235)   
8  (nan, -34.16196895703029)     (7.0, 7.33896423176618)   
9   (5.0, 4.993048633493229)   (3.0, 2.8690485751145625)   

               Space Odyssey  
0   (4.0, 3.979336350613533)  
1   (7.0, 6.966665946109118)  
2   (5.0, 4.999498086905717)  
3   (9.0, 8.999164535750015)  
4   (7.0, 7.027859893849413)  
5   (nan, 60.65109711753167)  
6   (7.0, 7.143382664224486)  
7   (9.0, 8.832381011610902)  
8  (3.0, 3.0494452637480833)  
9   (3.0, 2.999277022295093)

In [18]:
d = comparison_data.to_latex()
text_file = open("comparison.txt", "w")
text_file.write(d)
text_file.close()